Repository floornfts/mobile-minting, pull requests merged in 2024-10, with the labels that each got.

#56 Change minted on floor.fun to minted on rally.xyz
  src/ingestors/zora-internal/zora-metadata.ts
Labels: enhancement, Review effort [1-5]: 1

#57 Parse token ID for Rodeo mints
  src/ingestors/rodeo/index.ts
Labels: enhancement, Review effort [1-5]: 2

#58 Order Zora and Rodeo first for mobile mint ingesting
  src/ingestors/index.ts
Labels: enhancement, Review effort [1-5]: 1

#59 Disable highlight & fix some other tests.
  README.md
  src/ingestors/highlight/index.ts
  src/ingestors/highlight/offchain-metadata.ts
  test/ingestors/foundation.test.ts
  test/ingestors/highlight.test.ts
  test/ingestors/rarible.test.ts
Labels: enhancement, Review effort [1-5]: 3, tests

#61 Don't use sales strategies as a fallback for the end date for Zora
  src/ingestors/zora-internal/zora-metadata.ts
Labels: enhancement, Review effort [1-5]: 2
