Repository floornfts/mobile-minting, pull requests merged in 2024-09, with the labels that each got.

#50 Update ZORA default quantity to 1
  src/ingestors/zora-internal/zora-metadata.ts
Labels: enhancement, Review effort [1-5]: 1

#51 Fix Highlight tests. Add quantity support & contract export
  src/ingestors/highlight/index.ts
  src/ingestors/highlight/types.ts
  test/ingestors/highlight.test.ts
Labels: enhancement, Review effort [1-5]: 3, tests

#52 Update Branding
  README.md
Labels: documentation, Review effort [1-5]: 1
