Repository floornfts/mobile-minting, pull requests merged in 2024-08, with the labels that each got.

#36 Rodeo ingestion
  src/ingestors/rodeo/abi.ts
  src/ingestors/rodeo/index.ts
  src/ingestors/rodeo/offchain-metadata.ts
  src/ingestors/rodeo/onchain-metadata.ts
  test/ingestors/rodeo.test.ts
Labels: Review effort [1-5]: 3

#44 Export rodeo ingestor doh
  src/ingestors/index.ts
Labels: enhancement, Review effort [1-5]: 1

#24 raribleIngestor
  .github/workflows/tests.yaml
  .gitignore
  package.json
  src/ingestors/fxhash/index.ts
  src/ingestors/fxhash/offchain-metadata.ts
  src/ingestors/index.ts
  src/ingestors/prohibition-daily/index.ts
  src/ingestors/prohibition-daily/onchain-metadata.ts
  src/ingestors/rarible/abi.ts
  src/ingestors/rarible/index.ts
  src/ingestors/rarible/offchain-metadata.ts
  src/ingestors/rarible/onchain-metadata.ts
  src/lib/builder/mint-template-builder.ts
  test/ingestors/fxhash.test.ts
  test/ingestors/prohibition-daily.test.ts
  test/ingestors/rarible.test.ts
  yarn.lock
Labels: accepted, Review effort [1-5]: 4

#34 Ingestor wallet.coinbase
  src/ingestors/coinbase-wallet/abi.ts
  src/ingestors/coinbase-wallet/index.ts
  src/ingestors/coinbase-wallet/offchain-metadata.ts
  src/ingestors/coinbase-wallet/onchain-metadata.ts
  src/ingestors/coinbase-wallet/types.ts
  src/ingestors/index.ts
  test/ingestors/coinbase-wallet.test.ts
Labels: accepted, Review effort [1-5]: 3

#25 Add Manifold Base Mint Ingestor
  src/ingestors/index.ts
  src/ingestors/manifold/abi.ts
  src/ingestors/manifold/index.ts
  src/ingestors/manifold/offchain-metadata.ts
  src/ingestors/manifold/onchain-metadata.ts
  test/ingestors/manifold.test.ts
Labels: accepted, Review effort [1-5]: 4
